# le seul porte qu'ouvrira Docker-Compose sur votre machine sera le 443



# NGINX (avec TLS v1.2)
# WordPress (avec php-fpm configuré)
# MARIADB (sans NGINX)


services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
  wordpress:
    build: requirements/wordpress
    container_name: wp-php
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    
volumes:
  db_data:
    driver: local

networks:
  inc