# le seul port qu'ouvrira Docker-Compose sur votre machine sera le 443

# NGINX (avec TLS v1.2)
# WordPress (avec php-fpm configuré)
# MARIADB (sans NGINX)

services:
  mariadb:
      container_name: mariadb
      networks:
        - inception            			# à quel network il appartient
      build: 
        context: requirements/mariadb 	# ou se trouve son Dockerfile
        dockerfile: Dockerfile
      env_file: .env
      volumes:
        - mariadb:/var/lib/mysql
      restart: unless-stopped     # le container redemarre tant qu'il n'est pas stoppé
      expose:
        - "3306"

  nginx:
      container_name: nginx
      volumes:
        - wordpress:/var/www/wordpress
      networks:
        - inception
      depends_on:        			 # indique de ne pas démarrer NGINX tant que WordPress n'a pas démarré
        - wordpress
      build: 
        context: requirements/nginx
        dockerfile: Dockerfile
      env_file: .env
      ports:
        - "443:443" 		      # on indique le port qui sera exposé a la machine locale
      restart: on-failure 		# on change, le container redémarrera uniquement en cas de crash
  
  wordpress:
      container_name: wordpress
      env_file: .env
      volumes:
        - wordpress:/var/www/html
      networks:
        - inception
      build: 
        context: requirements/wordpress
        dockerfile: Dockerfile
      depends_on:    					# WordPress démarrera uniquement après MariaDB (sinon il ne pourra pas configurer la base de données...)
        - mariadb
      restart: on-failure
      expose: 
        - "9000"

volumes:
  wordpress:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: 'none' 									# aucun type spécifique
      o: 'bind'
      device: '${HOME}/data/wordpress' 		#Utilise une variable d'environnement
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'										 # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
      device: '${HOME}/data/mariadb'			#Utilise une variable d'environnement

networks:
  inception:
    driver: bridge # indique a Docker d'installer automatiquement des regles qui permettront aux 3 containers de communiquer entre eux en bridge